AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/IndentationWidth:
  Width: 2

Style/Semicolon:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 15
